config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :tasks do
    resources :subtasks, only: [:index, :new, :create]
    collection do
      post 'clear'
    end
  end

  resources :subtasks, only: [:show, :edit, :update, :destroy] do
  end

  resources :categories, only: [:index, :destroy, :create, :update]

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/categorising.rb
class Categorising < ApplicationRecord
  belongs_to :task
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  before_save { self.name = name.downcase.upcase_first }
  has_many :categorisings, dependent: :delete_all
  has_many :tasks, through: :categorisings
  validates :name, presence: true, uniqueness: { case_sensitive: false }
end

app/models/subtask.rb
class Subtask < ApplicationRecord
  before_create { self.completed = 0 }
  belongs_to :task
  validates :title, presence: true
end

app/models/task.rb
class Task < ApplicationRecord
  before_create { self.completed = 0 }
  before_save :combine_datetime_form_fields
  has_many :categorisings, dependent: :delete_all
  has_many :categories, through: :categorisings
  has_many :subtasks, dependent: :delete_all
  validates :title, presence: true
  validates :duedate, presence: true 

  # formatted list of categories associated with task
  def category_list
    categories.map(&:name).join(', ')
  end

  # for time input when editing tasks
  def time_field=(time)
    @duehour = time[4]
    @duemin = time[5]
  end

  def combine_datetime_form_fields
    if (@duehour and @duemin)
      self.duedate = self.duedate.change({ hour: @duehour, min: @duemin })
    end
  end
  

  # repeat tasks daily for heroku scheduler
  def self.repeat_tasks
    tasks = self.where(repeat: 1)
    tasks.each do |t|
      if t.completed
        t.duedate = Date.current.end_of_day.change(sec: 0)
        t.completed = 0
        t.subtasks.each do |s|
          s.completed = 0
          s.save
        end
        t.save
      end
    end
  end

  # priority number levels
  def priority_list 
    ['None', 'Low', 'Med', 'High']
  end

  def priority_level
    priority_list[self.priority]
  end

  # for _form. Selects categories to associate with task.
  def category_list=(ids)
    # to reject empty strings
    ids = ids.reject(&:empty?)
    self.categories = ids.map do |i|
      Category.find(i)
    end
  end

  # for _form. Checks whether category exists. Otherwise, make new.
  def new_category_list=(names)
    self.categories += names.split(',').map do |n|
      Category.where(name: n.downcase.strip.titleize).first_or_create!
    end
  end

  scope :priority_status, ->(level) { where(priority: level) if level.present? }
  scope :category_id, ->(id) { Category.find(id).tasks if id.present? }
  scope :status, ->(status) { where(completed: (status.present? ? status : 0)) }
  scope :date_group, ->(date_group) { 
    where("duedate <= ?", (date_group.blank? ? Date.today.end_of_day
            : 7.days.from_now.end_of_day)) unless date_group == 'Anytime' }

  # filtering in index
  def self.filter(filtering_params)
    task = self.where(nil)
    if filtering_params.empty?
      task = task.where(completed: 0).where("duedate <= ?", Date.today.end_of_day)
    else
      filtering_params.each do |key, value|
        task = task.public_send(key, value)
      end
    end
    task = task.order(duedate: :asc, priority: :desc, title: :asc)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all.order(name: :asc)

    respond_to do |format|
      format.html
      format.js { 
        @categories = 
          Category.where("name LIKE ?", "%#{params[:search]}%").order(name: :asc)
      } 
    end
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to categories_path
    end
  end

  def update
    @category = Category.find(params[:id])
    respond_to do |format|
      format.js {
        @category.update(name: params[:name])
        redirect_to categories_path
      }
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    redirect_to categories_path
  end

  private
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/subtasks_controller.rb
class SubtasksController < ApplicationController
  def new
    @task = Task.find(params[:task_id])
    @subtask = @task.subtasks.new
  end

  def edit
    @subtask = Subtask.find(params[:id])
  end

  def create
    @task = Task.find(params[:task_id])
    @subtask = @task.subtasks.new(subtask_params)

    respond_to do |format|
      format.html { 
        if @subtask.save
          redirect_to task_path(@task)
        else
          render 'tasks/show'
        end }
      format.js {
        if @subtask.save
          redirect_to task_path(@task)
        else
          render 'error'
        end }
    end
  end

  def update
    @subtask = Subtask.find(params[:id])

    respond_to do |format|
      format.html {
        if @subtask.update(subtask_params)
          redirect_to task_path(@subtask.task_id)
        else
          render 'edit'
        end
      }
      format.js { @subtask.update(completed: params[:completed]) 
                  redirect_to task_path(@subtask.task_id) }
    end
  end

  def destroy
    @subtask = Subtask.find(params[:id])
    @subtask.destroy

    redirect_to task_path(@subtask.task_id)
  end

  private
    def subtask_params
      params.require(:subtask).permit(:title, :completed)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    filter_cookies
    @tasks = Task.filter(filtering_params(params))
    @categories = Category.all
    
    respond_to do |format|
      format.html 
      format.js 
    end
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
    @task.priority = 0
  end

  def edit
    @task = Task.find(params[:id])
  end

  def create
    respond_to do |format|
      format.html {
        @task = Task.new(task_params)
        if @task.save
          redirect_to @task
        else
          render 'new'
        end
      }
      format.js {
        title, date, priority, category = params[:title], 
          params[:date], params[:priority], params[:category]
        @task = Task.new(title: title, duedate: date, priority: priority,
                         repeat: 0)
        @task.categories += Category.where(id: category)

        if @task.save
          redirect_to tasks_path
        end
      }
    end
  end

  def update
    @task = Task.find(params[:id])

    respond_to do |format|
      format.html {
        if @task.update(task_params)
          redirect_to @task
        else
          render 'edit'
        end
      }
      format.js { 
        if params[:completed]
          @task.update(completed: params[:completed]) 
        elsif params[:priority]
          @task.update(priority: params[:priority])
        end 
      }
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    redirect_to tasks_path
  end

  def clear
    Task.where(completed: true).where(repeat: false).destroy_all

    redirect_to tasks_path
  end

  private
    def task_params
      params.require(:task).permit(:title, :duedate, :repeat,
                                   { :category_list => [] }, 
                                   :new_category_list, :completed,
                                   :comments, :priority, :time_field)
    end

    def filter_cookies
      filter_vars = [:category_id, :date_group, :status, :priority_status]
      filter_vars.each do |key|
        if params[key]
          cookies[key] = { value: params[key], expires: 1.day.from_now }
        elsif cookies[key]
          params[key] = cookies[key]
        end
      end
    end

    def filtering_params(params)
      params.slice(:category_id, :date_group, :status, :priority_status)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    redirect_to tasks_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/subtasks_helper.rb
module SubtasksHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/_category.html.erb
<div class="index_row">
  <span class="name"><%= link_to category.name, 
    tasks_path(category_id: category.id, date_group: 'Anytime') %></span>
  <span class="count"><%= category.tasks.count %></span>
  <%= button_tag 'Edit', class: "edit", value: category.id %>
  <span class="destroy">
    <%= link_to category_path(category),
      method: :delete,
      data: { confirm: 'Are you sure?' } do %>
      <i class="fas fa-trash-alt"></i>
    <% end %>
  </span>
</div>

app/views/categories/index.html.erb
<h1>Categories</h1>

<%= text_field_tag 'category_search', nil, 
  autofocus: true, autocomplete: true, placeholder: "Search..." %>

<%= link_to 'Reset', categories_path %>

<div id="heading">
  <strong><span class="name">Name</span></strong>
  <strong><span class="count">Count</span></strong>
</div>
<%= form_with model: Category.new, url: '/categories', id: 'form' do |f| %>
  <div class="index_row">
    <%= f.text_field :name, placeholder: "Create new Category", class: "title",
        required: true %>
    <%= f.submit 'Create Category', class: "submit" %>
  </div>
<% end %>
<div id="category_listing">
  <% @categories.each do |category| %>
    <%= render partial: 'category', object: category %>
  <% end %>
</div>

app/views/categories/index.js.erb
document.getElementById('category_listing').innerHTML = 
  "<% @categories.each do |category| %>\
     <%= j render partial: 'category', object: category %>\
   <% end %>";

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <nav>
        <ul>
          <li><%= link_to 'Tasks', tasks_path %></li>
          <li><%= link_to 'Categories', categories_path %></li>
        </ul>
      </nav>
      <%= yield %>
    </div>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/subtasks/_form.html.erb
<div class="subtask_row">
  <%= form_with(model: @subtask || [ @task, @task.subtasks.build ], 
                url: @subtask ? @subtask.new_record? ? task_subtasks_path 
            : subtask_path : '/tasks/'+@task.id.to_s+'/subtasks' ) do |ff| %>
    <p>
      <%= ff.check_box :completed, class: "completed" if @subtask && !@subtask.new_record? %>
      <%= ff.text_field :title, placeholder: "Subtask Name", autofocus: true,
                                class: "title", required: true %>
      <%= ff.submit %>
    </p>
    <% if @subtask && @subtask.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@subtask.errors.count, "error") %> prohibited
          this subtask from being saved:
        </h2>
        <ul>
          <% @subtask.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  <% end %>
</div>

app/views/subtasks/_subtask.html.erb
<div class="subtask_row">
  <%= form_with model: subtask, url: subtask, local: true do |f| %>
    <%= check_box_tag 'subtasks', subtask.id, subtask.completed, 
        class: "completed" %>
    <span class="title">
      <span class="subtask_hide_<%= subtask.id %>"><%= subtask.title %></span>
      <%= f.text_field :title, required: true, 
                               class: "hidden_form_"+subtask.id.to_s %>
    </span>
    
    <%= link_to 'Edit', edit_subtask_path(subtask),
        class: "edit subtask_hide_"+subtask.id.to_s %>
    <%= f.submit class: "hidden_form_"+subtask.id.to_s %>
    <span class="destroy">
      <%= link_to subtask_path(subtask),
        method: :delete,
        data: { confirm: 'Are you sure?' } do %>
        <i class="fas fa-trash-alt"></i>
      <% end %>
    </span>
  <% end %>
</div>

app/views/subtasks/edit.html.erb
<h1>Edit Subtask</h1>
 
<%= render 'form' %><br>
 
<%= link_to 'Back', task_path(@subtask.task) %>

app/views/subtasks/error.js.erb
document.getElementById("new_subtask").innerHTML = 
  "<%= j render partial: 'form' %>"

app/views/tasks/_filter.html.erb
<h2>Filters</h2>
<%= form_with model: @category, method: :get, local: true do |f| %>
  <p>
    <%= f.label :date_group, "Due: " %>
    <%= f.select(:date_group, options_for_select(['Next 7 Days',
                                                  'Anytime'],
                                                  params[:date_group]),
                              { :include_blank => 'Today' }) %>
  </p>

  <p>
    <%= f.label :priority_status, "Priority: " %>
  <%= f.check_box :priority_status_0, 
    checked: (params[:priority_status].include?("0") rescue false) %>
  <span class='priority_flag none'>None</span>
  <%= f.check_box :priority_status_1, 
    checked: (params[:priority_status].include?("1") rescue false) %>
  <span class='priority_flag low'>Low</span>
  <%= f.check_box :priority_status_2,
    checked: (params[:priority_status].include?("2") rescue false) %>
  <span class='priority_flag med'>Med</span>
  <%= f.check_box :priority_status_3,
    checked: (params[:priority_status].include?("3") rescue false) %>
  <span class='priority_flag high'>High</span><br>


    <%= f.label :category_id, "Category: " %>
    <%= f.collection_select(:category_id, 
                            Category.all.order(name: :asc), :id, :name,
                            { :selected => params[:category_id], 
                              :include_blank => "All" }) %><br>
    <%= f.label :status, "Completed: " %>
    <%= f.check_box :status, checked: (params[:status] == 'true' ? true : false) %>
  </p>

  <p>
  <noscript><%= f.submit "Filter", name: nil %></noscript>
    <%= link_to 'Reset', tasks_path(category_id: "", date_group: "",
                                    status: 0, priority_status: "") %><br>
  </p>
<% end %>

app/views/tasks/_form.html.erb
<%= form_with model: @task, local: true do |f| %>

  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@task.errors.count, "error") %> prohibited 
            this task from being saved:
      </h2>
      <ul>
        <% @task.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="index_row">
    <% if @task.persisted? %>
      <%= f.check_box :completed, class: "completed" %>
    <% end %>

    <%= f.text_field :title, class: "edit_title", autofocus: true,
                             required: true, placeholder: "Go Shopping" %>
  </div>

  <p>
    <strong><%= f.label :duedate, "Due Date: " %></strong>
    <%= f.date_field :duedate, value: @task.persisted? ? @task.duedate.to_date : Date.today %>
    <%= f.time_select :time_field, 
      { default: { hour: (@task.persisted? ? @task.duedate.hour : 23),
                   minute: (@task.persisted? ? @task.duedate.min : 59) } } %>
  </p>
  
  <p>
    <strong><%= f.label :priority, "Priority: " %></strong>
    <%= f.select :priority, [['None', 0], ['Low', 1],
                             ['Med', 2], ['High', 3]] %>
  </p>

  <p>
    <strong><%= f.label :repeat, "Repeat Daily: " %></strong>
    <%= f.check_box :repeat %>
  </p>

  <p>
    <strong><%= f.label :comments, "Comments: " %></strong>
    <%= f.text_area :comments %>
  </p>

  <p>
    <strong><%= f.label :category_list, "Select Categories: " %></strong>
    <%= f.collection_select(:category_list,
                            Category.all.order(name: :asc), :id, :name,
                            { :selected => @task.categories.map do |t|
                                              t.id
                                              end,
                              :include_blank => true },
                            { :multiple => true }) %>
  </p>

  <p>
    <strong><%= f.label :new_category_list, "or create new Categories
                                     (seperated by ','): " %></strong><br>
    <%= f.text_field :new_category_list, placeholder: "School, Groceries, etc."  %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/tasks/_task.html.erb
<div class="index_row">
  <%= check_box_tag 'tasks', task.id, task.completed, 
    class: "completed" + (show ? " show" : "") %>
  <span class="title"><%= link_to task.title, task, 
    title: (task.comments.blank? ? "No Comments" : task.comments) %></span>
  <span class="date<%= task.duedate < Time.now ? " overdue"
  : "" %>"><%= task.duedate.strftime("%a, %d %b %y") %><br>
  <% if !(task.duedate.hour == 23 and task.duedate.min == 59) %>
    <%= task.duedate.strftime("%I:%M %p") %>
  <% end %>
  </span>
  <div class="dropdown priority">
    <div>
      <span class="priority_flag"><%= task.priority_level %></span>
      <div class="dropdown_content">
        <%= link_to task_path(task, priority: "0"),
          method: :patch, remote: true, class: "none" do %>
          <i class="fas fa-flag"></i>
        <% end %>
        <%= link_to task_path(task, priority: "1"),
          method: :patch, remote: true, class: "low" do %>
          <i class="fas fa-flag"></i>
        <% end %>
        <%= link_to task_path(task, priority: "2"),
          method: :patch, remote: true, class: "med" do %>
          <i class="fas fa-flag"></i>
        <% end %>
        <%= link_to task_path(task, priority: "3"),
          method: :patch, remote: true, class: "high" do %>
          <i class="fas fa-flag"></i>
        <% end %>
      </div>
    </div>
  </div>
  <span class="destroy">
    <%= link_to task_path(task),
      method: :delete,
      data: { confirm: 'Are you sure?' } do %>
      <i class="fas fa-trash-alt"></i>
    <% end %>
  </span>
</div>

app/views/tasks/edit.html.erb
<%= link_to 'Back', task_path(@task), class: "task_links" %>

<h1>Edit Task</h1>
 
<%= render 'form' %>
 

app/views/tasks/index.html.erb
<%= link_to 'New Task', new_task_path, id: "new_task", class: "task_links" %>

<h1>Tasks</h1>

<div id="filters">
  <%= render 'filter' %>
</div>

<%= button_to "Clear Completed Tasks", clear_tasks_path,
  data: { confirm: "Are you sure?" } %><br>

    
<div id="heading">
  <span class="completed">Completed</span>
  <strong><span class="title">Title</span></strong>
  <strong><span class="date">Due Date</span></strong>
  <strong><span class="priority">Priority</span></strong>
</div>
<div id="task_form">
  <div class="index_row">
    <span class="inv_box">Inv</span>
    <%= text_field_tag 'form_title', nil, placeholder: "Name of Task", 
      class: "title" %>
    <%= select_tag 'form_category',
    options_from_collection_for_select(@categories, "id", "name"),
    include_blank: "Choose a Category", class: "category" %>
    <%= date_field_tag 'form_date', Date.today, class: "date" %>
    <%= select_tag 'form_priority', options_for_select([['None', 0], ['Low', 1],
                                     ['Med', 2], ['High', 3]]), 
      class: "priority" %>
    <%= button_tag '>', data: { disable_with: "Creating..." },
      class: "submit", id: "form_submit" %>
  </div>
</div>
<div id="task_listing">
  <% @tasks.each do |task| %>
    <%= render partial: 'task', locals: { task: task, show: false } %>
  <% end %>
</div>

app/views/tasks/index.js.erb
document.getElementById('task_listing').innerHTML = 
  "<% @tasks.each do |task| %>\
 <%= j render partial: 'task', locals: { task: task, show: false } %>\
<% end %>";

priorityFunc();

app/views/tasks/new.html.erb
<%= link_to 'Back', tasks_path, class: "task_links" %>

<h1>New Task</h1>

<%= render 'form' %>

app/views/tasks/show.html.erb
<span class="task_links">
  <%= link_to 'Edit', edit_task_path(@task) %> | <%= link_to 'Back', tasks_path %>
</span>

<h1>Task Details</h1>

<div id="task_listing">
  <%= render partial: 'task', locals: { task: @task, show: true } %>
</div>

<div id="subtask_listings">
  <%= render @task.subtasks.order(completed: :asc) %>
</div>

<div id="new_subtask">
  <%= render partial: '/subtasks/form' %>
</div>

<p>
  <strong>Repeat Daily: </strong>
  <%= @task.repeat ? 'Yes' : 'No' %>
</p>

<p>
  <strong>Comments: </strong>
  <%= simple_format(@task.comments) %>
</p>

<p>
  <strong>Category: </strong>
  <%=@task.category_list %>
</p>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

<%= link_to 'My List', controller: 'tasks' %>